title: "Operating Systems 2021-1 (OS211)"
version: "February 2021"
copyright: "2021"
author: "Basyira Sabita"
address: "Jakarta"
urlweb: "https://basyirasabita.github.io/os211/"
urlgithub: "https://github.com/basyirasabita/os211/"
urlghpage: "https://basyirasabita.github.io/os211/"